all	6 6/dag

clean
  rm -rf [568vq] *.[568vq]

6
  mkdir 6

6/dag	main.6 dag.6
  6l -o 6/dag -L . main.6

dag.6	dag.go set.go target.go
  6g -o dag.6 dag.go set.go target.go

main.6	main.go dag.6
  6g -I . main.go
