#!/bin/bash

function t {
  EXPR=`eval bin/ls`
  test "$EXPR" = "$2"
  if [ $? = 0 ]
  then
    echo "PASS: '$1' = '$2'"
  else
    echo "FAIL: '$1' = '$2' WAS $EXPR"
  fi
}

t "", "Usage: ls [directory] [script.ls]"
t ".", "Usage: ls [directory] [script.ls]"
