#!/bin/bash

PASSED=0
FAILED=0

function t {
  e "$1"
  test "$EVAL" = "$2"
  if [ $? = 0 ]
  then
    echo "   PASS: '$1' = '$2'"
    pass
  else
    echo "   FAIL: '$1' = '$2' WAS '$EVAL'"
    fail
  fi
}

function m {
  if [[ $EVAL =~ $1 ]]
  then
    echo "   PASS: =~ '$1'"
    pass
  else
    echo "   FAIL: '$EVAL' !~ '$1' WAS '$EVAL'"
    fail
  fi
}

function e {
  EVAL=`eval bin/ls $1`
  echo -e ">> WITH args '$1'"
}

function pass {
  PASSED=$(($PASSED+1))
}

function fail {
  FAILED=$(($FAILED+1))
}

t "", "Usage: ls [directory] [script.ls]"
t ".", "Usage: ls [directory] [script.ls]"
t ". test/syntax-fail1.ls" "syntax error"
t ". test/syntax-fail2.ls" "syntax error"
t "nonexistentdir test/example.ls" "Couldn't stat nonexistentdir"

e "test/simpletree test/example.ls"
m "test/simpletree:"
m "test/simpletree/one"
m "test/simpletree/two"
m "test/simpletree/three"

e "test/complextree test/example.ls"
m "test/complextree:"
m "test/complextree:"
m "test/complextree/gamma"
m "test/complextree/beta"
m "test/complextree/alpha"
m "test/complextree/eins"
m "test/complextree/eins:"
m "test/complextree/eins/rawr"
m "test/complextree/eins/foobar"
m "test/complextree/eins/one"
m "test/complextree/eins/one:"
m "test/complextree/eins/one/foodir"
m "test/complextree/eins/one/foodir:"
m "test/complextree/eins/one/foodir/blah"

chmod 100 test/chmod100tree
e "test/chmod100tree test/example.ls"
m "Cannot get contents of test/chmod100tree"
chmod 644 test/chmod100tree

chmod 000 test/chmod600tree
chmod o+r test/chmod600tree
chmod o+w test/chmod600tree
e "test/chmod600tree test/example.ls"
m "Cannot get contents of test/chmod600tree"
chmod 644 test/chmod600tree

e "test/simpletree test/human_size.ls"
m "one.+2 B"
m "rit\.jpg.+58 KB"
m "dorms\.jpg.+1.1 MB"

echo -e "\n$PASSED passed, $FAILED failed"
