#!/bin/bash

function t {
  EXPR=`eval ./bin/expr $1`
  test "$EXPR" = "$2"
  if [ $? = 0 ]
  then
    echo "PASS: $1 = $2"
  else
    echo "FAIL: $1 = $2 WAS $EXPR"
  fi
}

t "1 + 1" 2
t "2 - 2" 0
t "6.0 / 3" 2
t "6 \* 3" 18
t "2 \* 10 / 4" 5
t "\( 1 \* 7 \) + 3" 10
t "40 / \( 8 + 2 \)" 4
t "2 + 2.5" 4.5
t "1.125 \* 8" 9
t "5 / 2" 2.5
t "40 / \( 8 + 2 \) + \( 10 \* 10 \) - 50" 54

t "42 / 0" "Division by zero"
t "\( 2 + 3" "No closing parenthesis"
t "1 \* \* 2" "Misplaced element *, check syntax"
t "+ 2" "Misplaced element +, check syntax"
t "1 / 2 /" "Misplaced element /, check syntax"
t "1 \* 2 \)" "Syntax error"
t "4 2" "Syntax error"
